dist: xenial
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-9" SEPARATE="ON"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - g++-9
        - boost1.70
        - cmake
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-9" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - g++-9
        - boost1.70
        - cmake
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - g++-8
        - boost1.70
        - cmake
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-7" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - g++-7
        - boost1.70
        - cmake
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" SEPARATE="ON"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - boost1.70
        - cmake
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - boost1.70
        - cmake
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-7" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - llvm-toolchain-xenial-7
        packages:
        - clang-7
        - boost1.70
        - cmake
  - os: osx
    language: cpp
    compiler: clang
    env: COMPILER="clang++" SEPARATE="OFF"

before_install:
- mkdir -p cmake
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    travis_retry wget "https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.tar.gz"
    tar xf cmake-3.15.4-Linux-x86_64.tar.gz -C cmake --strip-components=1
  else
    travis_retry wget "https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Darwin-x86_64.tar.gz"
    tar xf cmake-3.15.4-Darwin-x86_64.tar.gz -C cmake --strip-components=1
  fi
- export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
- cmake --version

script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFIND_BOOST=ON -DUSE_OPENMP=OFF -DBUILD_INTEGRATION_TEST=OFF -DSEPARATE_BUILD="${SEPARATE}" ..
- make VERBOSE=1
- ctest --output-on-failure
