dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-7" SEPARATE="ON"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - boost1.68
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-7" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - boost1.68
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-6" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - boost1.68
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-5" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - boost1.68
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-7" SEPARATE="ON"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
        packages:
        - clang-7
        - boost1.68
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-7" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
        packages:
        - clang-7
        - boost1.68
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-6.0" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - clang-6.0
        - boost1.68
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-5.0" SEPARATE="OFF"
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
        - boost1.68
  - os: osx
    language: cpp
    compiler: clang
    env: COMPILER="clang++" SEPARATE="OFF"

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p cmake
    travis_retry wget "https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.tar.gz"
    tar xf cmake-3.14.5-Linux-x86_64.tar.gz -C cmake --strip-components=1
    export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  fi
- cmake --version

script:
- mkdir build
- cd build
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFIND_BOOST=ON -DUSE_OPENMP=OFF -DBUILD_INTEGRATION_TEST=OFF -DSEPARATE_BUILD="${SEPARATE}" ..
  else
    cmake -DCMAKE_CXX_COMPILER=$COMPILER -DBOOST_ROOT=/usr/local/Cellar/boost/1.67.0_1/ -DUSE_OPENMP=OFF -DBUILD_INTEGRATION_TEST=OFF -DSEPARATE_BUILD="${SEPARATE}" ..
  fi
- make
- ctest --output-on-failure
