dist: xenial
language: cpp

matrix:
  INCLUDE:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-9" OMP_NUM_THREADS=4
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - g++-9
        - boost1.70
        - cmake

before_install:
- mkdir -p cmake
- travis_retry wget "https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.tar.gz"
- tar xf cmake-3.15.4-Linux-x86_64.tar.gz -C cmake --strip-components=1
- export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
- cmake --version

script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFIND_BOOST=ON -DUSE_OPENMP=ON -DBUILD_INTEGRATION_TEST=OFF -DSEPARATE_BUILD=ON ..
- make VERBOSE=1
- echo "OMP_NUM_THREADS=${OMP_NUM_THREADS}"
- ctest --output-on-failure
