[general]
precision     = "double"         # one of {"float", "double"}.
boundary      = "PeriodicCuboid" # one of {"PeriodicCuboid", "Unlimited"}
thread        = false            # enable threading parallelization
GPU           = false            # enable GPU parallelization
output_prefix = "excluded-volume"  # file prefix.
output_path   = "./"             # output path

[parameters]
kB   = 1.986231313e-3  # Boltzmann constant
NA   = 6.0221417930e23 # Avogadro constant
e    = 1.0             # elementary charge
"Îµ0" = 8.854187817e-12 # permittivity of vaccum

[simulator]
file_name = "input/excluded-volume/excluded-volume-langevin.toml"

[[systems]]
file_name = "input/excluded-volume/excluded-volume-system.toml"

[[forcefields]]
file_name = "input/excluded-volume/excluded-volume-forcefields.toml"
