[files]
output.prefix = "excluded-volume"         # file prefix.
output.path   = "./"                      # output path
output.format = "xyz"                     # output file format
input.path   = "./input/excluded-volume/" # input path

[units]
length = "angstrom" # "angstorm" or "Å" or "nm"
energy = "kcal/mol" # "kcal/mol" or "kJ/mol"

[simulator]
include = "excluded-volume-langevin.toml"

[[systems]]
include = "excluded-volume-system.toml"

[[forcefields]]
include = "excluded-volume-forcefields.toml"
