# vim: foldmethod=marker
[general]
precision     = "double"         # one of {"float", "double"}.
boundary      = "PeriodicCuboid" # one of {"PeriodicCuboid", "Unlimited"}
thread        = false            # enable threading parallelization
GPU           = false            # enable GPU parallelization
output_prefix = "lennard-jones"  # file prefix.
output_path   = "./"             # output path

[units]
length = "angstrom" # "angstorm" or "Å" or "nm"
energy = "kcal/mol" # "kcal/mol" or "kJ/mol"

[simulator]
file_name = "input/lennard-jones/lennard-jones-langevin.toml"

[[systems]]
file_name = "input/lennard-jones/lennard-jones-system.toml"

[[forcefields]]
file_name = "input/lennard-jones/lennard-jones-forcefields.toml"
