[simulator]
type          = "MolecularDynamics"
boundary_type = "PeriodicCuboid"
precision     = "double"
delta_t    = 0.01
total_step = 10000
save_step  = 100
integrator.type = "UnderdampedLangevin"
integrator.seed = 2374
integrator.parameters.size    = 4096
integrator.parameters.default = {gamma = 1.00}
