# vim: foldmethod=marker
[files]
output.prefix = "lennard-jones" # file prefix.
output.path   = "./"            # output path
output.format = "xyz"           # output file format
input.path    = "./input/lennard-jones/" # input path

[units]
length = "angstrom" # "angstorm" or "Å" or "nm"
energy = "kcal/mol" # "kcal/mol" or "kJ/mol"

[simulator]
include = "lennard-jones-langevin.toml"

[[systems]]
include = "lennard-jones-system.toml"

[[forcefields]]
include = "lennard-jones-forcefields.toml"
