[[forcefields.global]]
interaction = "Pair"
potential   = "LennardJones"
ignore.molecule = "Nothing"
ignore.particles_within.bond = 3
ignore.particles_within.contact = 1
spatial_partition.type   = "CellList"
spatial_partition.margin = 0.5
parameters.size    = 4096
parameters.default = {"σ" = 2.0, "ε" = 1.0}
