# vim: foldmethod=marker
[files]
output.prefix = "lennard-jones_"  # file prefix.
output.path   = "./"             # output path
input.path    = "./input/lennard-jones/" # input path

[units]
length = "angstrom" # "angstorm" or "Å" or "nm"
energy = "kcal/mol" # "kcal/mol" or "kJ/mol"

[simulator]
file_name = "lennard-jones-langevin.toml"

[[systems]]
file_name = "lennard-jones-system.toml"

[[forcefields]]
file_name = "lennard-jones-forcefields.toml"
