name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: Ubuntu-18.04
    strategy:
      matrix:
        compiler: ['g++-9', 'g++-8']
        separate: ['ON', 'OFF']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure
        run: |
            ls ${BOOST_ROOT_1_72_0}/lib
            mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DSEPARATE_BUILD=${{ matrix.separate }} -DBoost_USE_MULTITHREADED=ON -DBoost_ARCHITECTURE=-x64 -DBoost_ADDITIONAL_VERSIONS=1.72.0 -DBoost_DEBUG=ON -DFIND_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -DBOOST_ROOT=${BOOST_ROOT_1_72_0} -DUSE_OPENMP=ON -DBUILD_INTEGRATION_TEST=OFF
      - name: Build
        run: |
            cmake --build .
      - name: Test
        run: |
            ctest --output-on-failure
